-- 1. Enable uuid-ossp extension
create extension if not exists "uuid-ossp";

-- 2. Drop existing tables safely (Cascading drops all associated triggers automatically)
drop table if exists public.bookmarks cascade;
drop table if exists public.notes cascade;
drop table if exists public.reading_progress cascade;
drop table if exists public.user_progress cascade;
drop table if exists public.hadiths cascade;

-- 3. Create Hadiths cache table
create table public.hadiths (
    id integer primary key,
    number varchar(50) not null,
    kitab text not null,
    bab text not null,
    arabic text not null,
    translation text not null,
    kitab_arabic text,
    kitab_english text,
    bab_arabic text,
    bab_english text,
    english_narrator text,
    heading_arabic text,
    heading_english text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Bookmarks table
create table public.bookmarks (
    id bigint generated by default as identity primary key,
    user_id uuid default null,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint bookmarks_user_id_hadith_id_key unique (user_id, hadith_id)
);

-- 5. Create Notes table
create table public.notes (
    id bigint generated by default as identity primary key,
    user_id uuid default null,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint notes_user_id_hadith_id_key unique (user_id, hadith_id)
);

-- 6. Create Reading Progress table
create table public.reading_progress (
    id bigint generated by default as identity primary key,
    user_id uuid default null,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint reading_progress_user_id_key unique (user_id)
);

-- 7. Create User Progress table
create table public.user_progress (
    user_id uuid primary key default gen_random_uuid(),
    streak_count integer default 0 not null,
    last_read_date text,
    daily_goal integer default 5 not null,
    read_hadiths jsonb default '[]'::jsonb not null,
    read_history jsonb default '{}'::jsonb not null,
    settings jsonb default '{}'::jsonb not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Automatic Timestamp Trigger Setup
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

create trigger set_notes_updated_at
    before update on public.notes
    for each row
    execute function public.handle_updated_at();

create trigger set_progress_updated_at
    before update on public.reading_progress
    for each row
    execute function public.handle_updated_at();

create trigger set_user_progress_updated_at
    before update on public.user_progress
    for each row
    execute function public.handle_updated_at();

-- 9. Performance Indexes
create index idx_hadiths_number on public.hadiths(number);
create index idx_hadiths_kitab on public.hadiths(kitab);
create index idx_bookmarks_hadith_id on public.bookmarks(hadith_id);
create index idx_bookmarks_user_id on public.bookmarks(user_id);
create index idx_notes_hadith_id on public.notes(hadith_id);
create index idx_notes_user_id on public.notes(user_id);
create index idx_progress_user_id on public.reading_progress(user_id);

-- 10. Enable Row Level Security (RLS)
alter table public.hadiths enable row level security;
alter table public.bookmarks enable row level security;
alter table public.notes enable row level security;
alter table public.reading_progress enable row level security;
alter table public.user_progress enable row level security;

-- 11. Policies
create policy "Allow public read of hadiths" on public.hadiths for select using (true);
create policy "Allow public insert of hadiths" on public.hadiths for insert with check (true);

create policy "Allow public read of bookmarks" on public.bookmarks for select using (true);
create policy "Allow public insert of bookmarks" on public.bookmarks for insert with check (true);
create policy "Allow public delete of bookmarks" on public.bookmarks for delete using (true);

create policy "Allow public read of notes" on public.notes for select using (true);
create policy "Allow public insert of notes" on public.notes for insert with check (true);
create policy "Allow public update of notes" on public.notes for update using (true);
create policy "Allow public delete of notes" on public.notes for delete using (true);

create policy "Allow public read of progress" on public.reading_progress for select using (true);
create policy "Allow public insert of progress" on public.reading_progress for insert with check (true);
create policy "Allow public update of progress" on public.reading_progress for update using (true);

create policy "Allow public read of user_progress" on public.user_progress for select using (true);
create policy "Allow public insert of user_progress" on public.user_progress for insert with check (true);
create policy "Allow public update of user_progress" on public.user_progress for update using (true);
create policy "Allow public delete of user_progress" on public.user_progress for delete using (true);

-- 12. Seed Initial Hadiths
insert into public.hadiths (id, number, kitab, bab, arabic, translation, kitab_arabic, kitab_english, bab_arabic, bab_english) values
(1, '1', 'Revelation', 'How the Divine Revelation started', 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى دُنْيَا يُصِيبُهَا أَوْ إِلَى امْرَأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ', 'The reward of deeds depends upon the intentions and every person will get the reward according to what he has intended. So whoever emigrated for worldly benefits or for a woman to marry, his emigration was for what he emigrated for.', 'كتاب بدء الوحى', 'Revelation', 'كَيْفَ كَانَ بَدْءُ الْوَحْىِ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم', 'How the Divine Revelation started being revealed to Allah''s Messenger (peace be upon him)'),
(2, '2', 'Belief (Faith)', 'Islam is based on five (principles)', 'بُنِيَ الإِسْلاَمُ عَلَى خَمْسٍ شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلاَةِ، وَإِيتَاءِ الزَّكَاةِ، وَالْحَجِّ، وَصَوْمِ رَمَضَانَ', 'Islam is based on the following five (principles): To testify that none has the right to be worshipped but Allah and Muhammad is Allah''s Messenger. To offer the (compulsory congregational) prayers dutifully and perfectly. To pay Zakat (i.e. obligatory charity). To perform Hajj. (i.e. Pilgrimage to Mecca). To observe fast during the month of Ramadan.', 'كتاب الإيمان', 'Belief (Faith)', 'باب دُعَاؤُكُمْ إِيمَانُكُمْ', 'Islam is based on five (principles)'),
(3, '13', 'Belief (Faith)', 'To love the Prophet (ﷺ) is a part of Faith', 'لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى أَكُونَ أَحَبَّ إِلَيْهِ مِنْ وَالِدِهِ وَوَلَدِهِ وَالنَّاسِ أَجْمَعِينَ', 'None of you will have faith till he loves me more than his father, his children and all mankind.', 'كتاب الإيمان', 'Belief (Faith)', 'باب حُبِّ الرَّسُولِ صلى الله عليه وسلم مِنَ الإِيمَانِ', 'To love the Prophet (ﷺ) is a part of Faith'),
(4, '15', 'Belief (Faith)', 'To love for one''s brother what one loves for oneself is a part of Faith', 'لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', 'None of you will have faith till he wishes for his (Muslim) brother what he likes for himself.', 'كتاب الإيمان', 'Belief (Faith)', 'باب مِنَ الإِيمَانِ أَنْ يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', 'To love for one''s brother what one loves for oneself is a part of Faith')
on conflict (id) do nothing;
