-- ==========================================
-- SAHIH AL-BUKHARI PORTAL - DATABASE SCHEMA
-- For Supabase PostgreSQL Setup
-- ==========================================

-- Enable any required extensions
create extension if not exists "uuid-ossp";

-- 1. HADITHS CACHE TABLE
-- Caches hadith metadata to satisfy foreign keys and speed up lookups
create table if not exists public.hadiths (
    id integer primary key,
    number varchar(50) not null,
    kitab text not null,
    bab text not null,
    arabic text not null,
    translation text not null,
    kitab_arabic text,
    kitab_english text,
    bab_arabic text,
    bab_english text,
    english_narrator text,
    heading_arabic text,
    heading_english text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. BOOKMARKS TABLE
-- Tracks user-saved hadiths
create table if not exists public.bookmarks (
    id bigint generated by default as identity primary key,
    user_id uuid default null,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint bookmarks_user_id_hadith_id_key unique (user_id, hadith_id)
);

-- 3. NOTES TABLE
-- Allows saving personal reflections on specific hadiths
create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    user_id uuid default null,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint notes_user_id_hadith_id_key unique (user_id, hadith_id)
);

-- 4. READING PROGRESS TABLE
-- Stores the latest reading position
create table if not exists public.reading_progress (
    id bigint generated by default as identity primary key,
    user_id uuid default null,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint reading_progress_user_id_key unique (user_id)
);

-- 5. USER PROGRESS TABLE
-- Stores streaks, goals, read list, and synced user settings
create table if not exists public.user_progress (
    user_id uuid primary key default gen_random_uuid(),
    streak_count integer default 0 not null,
    last_read_date text,
    daily_goal integer default 5 not null,
    read_hadiths jsonb default '[]'::jsonb not null,
    read_history jsonb default '{}'::jsonb not null,
    settings jsonb default '{}'::jsonb not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- AUTOMATIC TIMESTAMP TRIGGERS
-- ==========================================

-- Function to handle update timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

-- Apply trigger to notes
drop trigger if exists set_notes_updated_at on public.notes;
create trigger set_notes_updated_at
    before update on public.notes
    for each row
    execute function public.handle_updated_at();

-- Apply trigger to reading_progress
drop trigger if exists set_progress_updated_at on public.reading_progress;
create trigger set_progress_updated_at
    before update on public.reading_progress
    for each row
    execute function public.handle_updated_at();

-- Apply trigger to user_progress
drop trigger if exists set_user_progress_updated_at on public.user_progress;
create trigger set_user_progress_updated_at
    before update on public.user_progress
    for each row
    execute function public.handle_updated_at();

-- ==========================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- ==========================================

-- Hadith indices for quick indexing and searching
create index if not exists idx_hadiths_number on public.hadiths(number);
create index if not exists idx_hadiths_kitab on public.hadiths(kitab);

-- Bookmark indices
create index if not exists idx_bookmarks_hadith_id on public.bookmarks(hadith_id);
create index if not exists idx_bookmarks_user_id on public.bookmarks(user_id);

-- Note indices
create index if not exists idx_notes_hadith_id on public.notes(hadith_id);
create index if not exists idx_notes_user_id on public.notes(user_id);

-- Progress indices
create index if not exists idx_progress_user_id on public.reading_progress(user_id);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on all tables
alter table public.hadiths enable row level security;
alter table public.bookmarks enable row level security;
alter table public.notes enable row level security;
alter table public.reading_progress enable row level security;
alter table public.user_progress enable row level security;

-- Hadiths Policies: Anyone can read or cache hadiths
drop policy if exists "Allow public read of hadiths" on public.hadiths;
create policy "Allow public read of hadiths" on public.hadiths for select using (true);

drop policy if exists "Allow public insert of hadiths" on public.hadiths;
create policy "Allow public insert of hadiths" on public.hadiths for insert with check (true);

-- Bookmarks Policies: Anyone can manage bookmarks
drop policy if exists "Allow public read of bookmarks" on public.bookmarks;
create policy "Allow public read of bookmarks" on public.bookmarks for select using (true);

drop policy if exists "Allow public insert of bookmarks" on public.bookmarks;
create policy "Allow public insert of bookmarks" on public.bookmarks for insert with check (true);

drop policy if exists "Allow public delete of bookmarks" on public.bookmarks;
create policy "Allow public delete of bookmarks" on public.bookmarks for delete using (true);

-- Notes Policies: Anyone can manage notes
drop policy if exists "Allow public read of notes" on public.notes;
create policy "Allow public read of notes" on public.notes for select using (true);

drop policy if exists "Allow public insert of notes" on public.notes;
create policy "Allow public insert of notes" on public.notes for insert with check (true);

drop policy if exists "Allow public update of notes" on public.notes;
create policy "Allow public update of notes" on public.notes for update using (true);

drop policy if exists "Allow public delete of notes" on public.notes;
create policy "Allow public delete of notes" on public.notes for delete using (true);

-- Reading Progress Policies: Anyone can manage reading progress
drop policy if exists "Allow public read of progress" on public.reading_progress;
create policy "Allow public read of progress" on public.reading_progress for select using (true);

drop policy if exists "Allow public insert of progress" on public.reading_progress;
create policy "Allow public insert of progress" on public.reading_progress for insert with check (true);

drop policy if exists "Allow public update of progress" on public.reading_progress;
create policy "Allow public update of progress" on public.reading_progress for update using (true);

-- User Progress Policies: Anyone can manage user progress
drop policy if exists "Allow public read of user_progress" on public.user_progress;
create policy "Allow public read of user_progress" on public.user_progress for select using (true);

drop policy if exists "Allow public insert of user_progress" on public.user_progress;
create policy "Allow public insert of user_progress" on public.user_progress for insert with check (true);

drop policy if exists "Allow public update of user_progress" on public.user_progress;
create policy "Allow public update of user_progress" on public.user_progress for update using (true);

drop policy if exists "Allow public delete of user_progress" on public.user_progress;
create policy "Allow public delete of user_progress" on public.user_progress for delete using (true);


-- =========================================================================
-- --- MIGRATION FOR PERSISTENT SYNC (RUN THIS FOR EXISTING DATABASES) ---
-- =========================================================================
-- Copy and run the query block below in the Supabase Dashboard SQL Editor:
/*
-- 1. Enable uuid-ossp extension
create extension if not exists "uuid-ossp";

-- 2. Modify bookmarks table
alter table public.bookmarks add column if not exists user_id uuid default null;
alter table public.bookmarks drop constraint if exists bookmarks_user_id_hadith_id_key;
alter table public.bookmarks add constraint bookmarks_user_id_hadith_id_key unique (user_id, hadith_id);
create index if not exists idx_bookmarks_user_id on public.bookmarks(user_id);

-- 3. Modify notes table
alter table public.notes add column if not exists user_id uuid default null;
alter table public.notes drop constraint if exists notes_hadith_id_key;
alter table public.notes drop constraint if exists notes_user_id_hadith_id_key;
alter table public.notes add constraint notes_user_id_hadith_id_key unique (user_id, hadith_id);
create index if not exists idx_notes_user_id on public.notes(user_id);

-- 4. Modify reading_progress table
alter table public.reading_progress add column if not exists user_id uuid default null;
alter table public.reading_progress drop constraint if exists reading_progress_user_id_key;
alter table public.reading_progress add constraint reading_progress_user_id_key unique (user_id);
create index if not exists idx_progress_user_id on public.reading_progress(user_id);

-- 5. Create user_progress table
create table if not exists public.user_progress (
    user_id uuid primary key default gen_random_uuid(),
    streak_count integer default 0 not null,
    last_read_date text,
    daily_goal integer default 5 not null,
    read_hadiths jsonb default '[]'::jsonb not null,
    read_history jsonb default '{}'::jsonb not null,
    settings jsonb default '{}'::jsonb not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS and setup policies for user_progress
alter table public.user_progress enable row level security;

drop policy if exists "Allow public read of user_progress" on public.user_progress;
create policy "Allow public read of user_progress" on public.user_progress for select using (true);

drop policy if exists "Allow public insert of user_progress" on public.user_progress;
create policy "Allow public insert of user_progress" on public.user_progress for insert with check (true);

drop policy if exists "Allow public update of user_progress" on public.user_progress;
create policy "Allow public update of user_progress" on public.user_progress for update using (true);

drop policy if exists "Allow public delete of user_progress" on public.user_progress;
create policy "Allow public delete of user_progress" on public.user_progress for delete using (true);

-- Add update trigger for user_progress
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

drop trigger if exists set_user_progress_updated_at on public.user_progress;
create trigger set_user_progress_updated_at
    before update on public.user_progress
    for each row
    execute function public.handle_updated_at();
*/
