-- ==========================================
-- SAHIH AL-BUKHARI PORTAL - DATABASE SCHEMA
-- For Supabase PostgreSQL Setup
-- ==========================================

-- Enable any required extensions
create extension if not exists "uuid-ossp";

-- 1. HADITHS CACHE TABLE
-- Caches hadith metadata to satisfy foreign keys and speed up lookups
create table if not exists public.hadiths (
    id integer primary key,
    number varchar(50) not null,
    kitab text not null,
    bab text not null,
    arabic text not null,
    translation text not null,
    kitab_arabic text,
    kitab_english text,
    bab_arabic text,
    bab_english text,
    english_narrator text,
    heading_arabic text,
    heading_english text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. BOOKMARKS TABLE
-- Tracks user-saved hadiths
create table if not exists public.bookmarks (
    id bigint generated by default as identity primary key,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. NOTES TABLE
-- Allows saving personal reflections on specific hadiths
create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    hadith_id integer not null unique references public.hadiths(id) on delete cascade,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. READING PROGRESS TABLE
-- Stores the latest reading position
create table if not exists public.reading_progress (
    id bigint generated by default as identity primary key,
    hadith_id integer not null references public.hadiths(id) on delete cascade,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- AUTOMATIC TIMESTAMP TRIGGERS
-- ==========================================

-- Function to handle update timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

-- Apply trigger to notes
create trigger set_notes_updated_at
    before update on public.notes
    for each row
    execute function public.handle_updated_at();

-- Apply trigger to reading_progress
create trigger set_progress_updated_at
    before update on public.reading_progress
    for each row
    execute function public.handle_updated_at();

-- ==========================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- ==========================================

-- Hadith indices for quick indexing and searching
create index if not exists idx_hadiths_number on public.hadiths(number);
create index if not exists idx_hadiths_kitab on public.hadiths(kitab);

-- Bookmark indices to join bookmarks and hadiths efficiently
create index if not exists idx_bookmarks_hadith_id on public.bookmarks(hadith_id);

-- Note indices
create index if not exists idx_notes_hadith_id on public.notes(hadith_id);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on all tables
alter table public.hadiths enable row level security;
alter table public.bookmarks enable row level security;
alter table public.notes enable row level security;
alter table public.reading_progress enable row level security;

-- Hadiths Policies: Anyone (anon / authenticated) can read or insert new records to cache
create policy "Allow public read of hadiths"
    on public.hadiths for select
    using (true);

create policy "Allow public insert of hadiths"
    on public.hadiths for insert
    with check (true);

-- Bookmarks Policies: Anyone (anon) can view, insert, or delete bookmarks
create policy "Allow public read of bookmarks"
    on public.bookmarks for select
    using (true);

create policy "Allow public insert of bookmarks"
    on public.bookmarks for insert
    with check (true);

create policy "Allow public delete of bookmarks"
    on public.bookmarks for delete
    using (true);

-- Notes Policies: Anyone can view, insert, update, or delete notes
create policy "Allow public read of notes"
    on public.notes for select
    using (true);

create policy "Allow public insert of notes"
    on public.notes for insert
    with check (true);

create policy "Allow public update of notes"
    on public.notes for update
    using (true);

create policy "Allow public delete of notes"
    on public.notes for delete
    using (true);

-- Reading Progress Policies: Anyone can view, insert, or update reading progress
create policy "Allow public read of progress"
    on public.reading_progress for select
    using (true);

create policy "Allow public insert of progress"
    on public.reading_progress for insert
    with check (true);

create policy "Allow public update of progress"
    on public.reading_progress for update
    using (true);
